version: '3.8'
services:
  cache-redis:
    image: redis:latest
    container_name: cache-sre
    networks:
      - sre-net
    ports:
      - "6380:6379"

  mysql-db:
    image: mysql:8
    container_name: web-db
    networks:
      - sre-net
    env_file:
      - ./mysql/mysql.env
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"
    restart: always

  web-server:
    image: huaiwei/remote4:latest
    container_name: web-sre
    networks:
      - sre-net
    env_file:
      - ./web-sre.env
    ports:
      - "3000:3000"
    depends_on:
      - mysql-db
      - cache-redis
    restart: on-failure

  nginx-proxy: 
    image: nginx:latest
    container_name: nginx-sre
    networks:
      - sre-net
    depends_on:
      - web-server
      - cache-redis
      - mysql-db
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

networks:
  sre-net:
